"use client"

import { useState } from "react"
import { ArrowDown, ArrowRight, Check, ChevronDown, CircleHelp, Clock3, Menu, ShieldCheck, Sparkles, Star, X } from "lucide-react"

const navItems = ["Обзор", "Бонусы", "Игры", "Платежи", "Отзывы", "FAQ"]
const facts = [["Год запуска", "2024"], ["Лицензия", "Демо-данные"], ["Минимальный депозит", "500 ₽"], ["Вывод", "от 15 минут*"]]
const games = [{ name: "Слоты", detail: "2 500+ игр", tone: "gold" }, { name: "Live Casino", detail: "Рулетка и покер", tone: "green" }, { name: "Джекпоты", detail: "Прогрессивные", tone: "blue" }]
const faqs = [["Velora Casino — это официальное казино?", "Страница содержит демо-данные для макета. Перед публикацией обязательно проверьте юридический статус, домен и действующую лицензию клуба."], ["Какой бонус доступен новым игрокам?", "В демонстрационном сценарии показан приветственный бонус 100% до 30 000 ₽. Фактические условия акции необходимо подтвердить на официальном сайте."], ["Сколько занимает вывод средств?", "В макете указано от 15 минут, но скорость зависит от метода оплаты, верификации и регламента оператора."]]

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [openFaq, setOpenFaq] = useState(0)
  const anchor = (item: string) => `#${item.toLowerCase().replace(" ", "-")}`

  return <main className="min-h-screen bg-background text-foreground">
    <div className="demo-bar"><div className="container flex items-center justify-center gap-2 py-2 text-center text-xs text-primary-foreground/80"><CircleHelp className="size-3.5" aria-hidden="true" /><span>Демо-страница: фактические параметры и предложения требуют проверки перед публикацией.</span></div></div>
    <header className="sticky top-0 z-30 border-b border-border/70 bg-background/95 backdrop-blur-md"><div className="container flex h-18 items-center justify-between gap-6"><a href="#top" className="flex items-center gap-3" aria-label="Velora Casino — на главную"><span className="brand-mark"><Sparkles className="size-4" aria-hidden="true" /></span><span className="font-serif text-xl font-semibold tracking-tight">velora<span className="text-accent">.</span></span></a><nav className="hidden items-center gap-7 md:flex" aria-label="Основная навигация">{navItems.map(item => <a key={item} href={anchor(item)} className="nav-link">{item}</a>)}</nav><div className="hidden items-center gap-3 sm:flex"><a href="#reviews" className="button-ghost">Отзывы <ArrowRight className="size-4" aria-hidden="true" /></a><a href="#bonus" className="button-primary">Получить бонус</a></div><button className="flex size-10 items-center justify-center rounded-full border border-border md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? "Закрыть меню" : "Открыть меню"} aria-expanded={menuOpen}>{menuOpen ? <X className="size-5" /> : <Menu className="size-5" />}</button></div>{menuOpen && <nav className="container flex flex-col gap-1 border-t border-border py-4 md:hidden" aria-label="Мобильная навигация">{navItems.map(item => <a key={item} onClick={() => setMenuOpen(false)} href={anchor(item)} className="rounded-lg px-3 py-2 text-sm hover:bg-muted">{item}</a>)}<a href="#bonus" className="button-primary mt-2 justify-center">Получить бонус</a></nav>}</header>
    <section id="top" className="hero-section"><div className="container grid items-center gap-12 py-18 lg:grid-cols-[1.08fr_.92fr] lg:py-24"><div className="max-w-2xl"><div className="eyebrow"><span className="status-dot" /> Актуальный обзор · 2026</div><h1 className="mt-6 font-serif text-5xl font-medium leading-[1.02] tracking-tight text-balance sm:text-6xl lg:text-7xl">Velora Casino: <em>игра</em> с ясными правилами</h1><p className="mt-6 max-w-xl text-base leading-7 text-muted-foreground sm:text-lg">Разбираем платформу без лишнего шума: бонусы, каталог игр, платежи и пользовательский опыт в одном честном обзоре.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#bonus" className="button-primary justify-center">Перейти к бонусу <ArrowRight className="size-4" aria-hidden="true" /></a><a href="#overview" className="button-ghost justify-center">Читать обзор <ArrowDown className="size-4" aria-hidden="true" /></a></div><div className="mt-9 flex flex-wrap items-center gap-x-6 gap-y-3 text-xs text-muted-foreground"><span className="flex items-center gap-2"><ShieldCheck className="size-4 text-accent" /> Проверяем условия</span><span className="flex items-center gap-2"><Clock3 className="size-4 text-accent" /> Обновлено сегодня</span></div></div><div className="hero-card"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.18em] text-muted-foreground">Оценка редакции</p><div className="mt-3 flex items-end gap-2"><span className="font-serif text-6xl leading-none">4.8</span><span className="mb-1 text-sm text-muted-foreground">/ 5</span></div></div><div className="score-badge"><Star className="size-4 fill-current" /> Отлично</div></div><div className="mt-8 grid grid-cols-5 gap-1.5" aria-label="Рейтинг 4.8 из 5">{[1,2,3,4,5].map(n => <span key={n} className={`rating-bar ${n === 5 ? "rating-partial" : ""}`} />)}</div><div className="mt-8 border-t border-border pt-6"><p className="text-sm leading-6 text-muted-foreground">Сбалансированный выбор для тех, кто ценит большую библиотеку игр и понятную навигацию.</p><div className="mt-5 flex items-center justify-between text-xs"><span className="text-muted-foreground">Последняя проверка</span><span className="font-medium">09.09.2026</span></div></div></div></div></section>
    <section id="overview" className="container py-16 sm:py-20"><div className="section-heading"><div><p className="eyebrow">Коротко о главном</p><h2 className="mt-3 font-serif text-4xl tracking-tight sm:text-5xl">Velora в цифрах</h2></div><p className="max-w-sm text-sm leading-6 text-muted-foreground">Основные сведения собраны в одном месте. Звёздочкой отмечены параметры, которые нужно подтвердить.</p></div><div className="mt-10 grid border-y border-border sm:grid-cols-2 lg:grid-cols-4">{facts.map(([label, value], i) => <div key={label} className={`fact-cell ${i % 2 ? "sm:border-l" : ""} lg:border-l lg:first:border-l-0`}><p className="text-xs uppercase tracking-[.16em] text-muted-foreground">{label}</p><p className="mt-3 font-serif text-2xl">{value}<sup className="text-accent">{label === "Вывод" ? "*" : ""}</sup></p></div>)}</div><p className="mt-4 text-xs text-muted-foreground">* Демонстрационные данные. Требуют проверки по официальным источникам.</p></section>
    <section id="bonus" className="container pb-16 sm:pb-20"><div className="bonus-panel"><div className="max-w-xl"><div className="eyebrow text-accent"><Sparkles className="size-3.5" /> Демо-сценарий</div><h2 className="mt-4 font-serif text-4xl leading-tight tracking-tight sm:text-5xl">Стартуйте с бонусом <em>100%</em></h2><p className="mt-4 max-w-md text-sm leading-6 text-primary-foreground/65">До 30 000 ₽ на первый депозит. Пример оффера для презентации — условия акции нужно подтвердить перед запуском.</p></div><div className="flex flex-col items-start gap-4 sm:items-end"><div className="bonus-amount">30 000 <span>₽</span></div><a href="#games" className="button-accent">Смотреть условия <ArrowRight className="size-4" /></a></div></div></section>
    <section id="games" className="border-y border-border bg-muted/35"><div className="container py-16 sm:py-20"><div className="section-heading"><div><p className="eyebrow">Каталог</p><h2 className="mt-3 font-serif text-4xl tracking-tight sm:text-5xl">Играйте в своё</h2></div><a href="#reviews" className="hidden text-sm font-medium text-accent sm:flex sm:items-center sm:gap-2">Все категории <ArrowRight className="size-4" /></a></div><div className="mt-10 grid gap-4 md:grid-cols-3">{games.map((game, i) => <article key={game.name} className={`game-card game-${game.tone}`}><div className="game-number">0{i + 1}</div><div className="mt-18"><h3 className="font-serif text-3xl">{game.name}</h3><p className="mt-2 text-sm text-muted-foreground">{game.detail}</p></div><ArrowRight className="absolute bottom-6 right-6 size-5" /></article>)}</div></div></section>
    <section id="reviews" className="container py-16 sm:py-20"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Мнение игроков</p><h2 className="mt-3 font-serif text-4xl tracking-tight sm:text-5xl">Что говорят<br /><em>наши читатели</em></h2><p className="mt-5 max-w-sm text-sm leading-6 text-muted-foreground">Тестовые отзывы для демонстрации блока. Перед публикацией замените их на реальные, проверяемые источники.</p></div><div className="review-list"><article className="review-item"><div className="flex items-center justify-between"><div className="flex gap-1 text-accent">{[1,2,3,4,5].map(n => <Star key={n} className="size-3.5 fill-current" />)}</div><span className="text-xs text-muted-foreground">Демо-отзыв</span></div><p className="mt-5 text-lg leading-7">«Понравилось, что всё находится под рукой: от выбора игры до статуса платежа. Интерфейс не отвлекает от главного.»</p><p className="mt-5 text-xs font-medium uppercase tracking-[.14em]">Алексей · Москва</p></article><article className="review-item"><div className="flex items-center justify-between"><div className="flex gap-1 text-accent">{[1,2,3,4,5].map(n => <Star key={n} className="size-3.5 fill-current" />)}</div><span className="text-xs text-muted-foreground">Демо-отзыв</span></div><p className="mt-5 text-lg leading-7">«Большой выбор слотов и понятные условия бонуса. Хотелось бы больше способов оплаты.»</p><p className="mt-5 text-xs font-medium uppercase tracking-[.14em]">Марина · Казань</p></article></div></div></section>
    <section id="faq" className="border-t border-border"><div className="container grid gap-10 py-16 sm:py-20 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">FAQ</p><h2 className="mt-3 font-serif text-4xl tracking-tight sm:text-5xl">Частые<br /><em>вопросы</em></h2></div><div className="faq-list">{faqs.map(([question, answer], i) => <div key={question} className="faq-item"><button className="flex w-full items-center justify-between gap-4 py-5 text-left font-medium" onClick={() => setOpenFaq(openFaq === i ? -1 : i)} aria-expanded={openFaq === i}><span>{question}</span><ChevronDown className={`size-5 shrink-0 text-accent transition-transform ${openFaq === i ? "rotate-180" : ""}`} /></button>{openFaq === i && <p className="pb-5 pr-8 text-sm leading-6 text-muted-foreground">{answer}</p>}</div>)}</div></div></section>
    <footer className="border-t border-border bg-muted/30"><div className="container flex flex-col gap-6 py-8 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2 font-serif text-base text-foreground"><span className="brand-mark size-7"><Sparkles className="size-3" /></span> velora<span className="text-accent">.</span></div><p>18+ · Играйте ответственно · Демо-страница обзора</p><p>© 2026 Velora Review</p></div></footer>
  </main>
}
